### ISSUE TITLE
AttributeError: 'TNews' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by myhostone1990** [FlagOpen/FlagEmbedding#679]

**Comment by markma0617** [comment]
same question,here is my traceback:
>>> python C_MTEB/eval_C-MTEB.py --model_name_or_path examples/finetune/mixed_model
Traceback (most recent call last):
  File "/root/autodl-tmp/FlagEmbedding/C_MTEB/eval_C-MTEB.py", line 35, in <module>
    task_names = [t.description["name"] for t in MTEB(task_types=args.task_type,
  File "/root/miniconda3/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 74, in __init__
    self.select_tasks(**kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 161, in select_tasks
    self.tasks_cls = [
  File "/root/miniconda3/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 162, in <listcomp>
    cls(langs=self._task_langs, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 45, in __init__
    else self.metadata_dict.get("n_experiments", 10)
  File "/root/miniconda3/lib/python3.10/site-packages/mteb/abstasks/AbsTask.py", line 48, in metadata_dict
    metadata_dict = dict(self.metadata)
AttributeError: 'TNews' object has no attribute 'metadata'

**Comment by staoxiao** [comment]
可以降低mteb版本试试。https://github.com/FlagOpen/FlagEmbedding/issues/531

**Comment by markma0617** [comment]
> 可以降低mteb版本试试。#531

可以发一下你的mteb版本号吗？

**Comment by dantengA** [comment]
i can work with it using mteb-1.2.0.

**Comment by myhostone1990** [comment]
> i can work with it using mteb-1.2.0.

可以了，多谢
